import Head from "next/head";

import Image from "next/image";
import styles from "../../styles/Home.module.scss";
import react, { useState, useEffect } from "react";
import Link from "next/link";
import ReactReadMoreReadLess from "react-read-more-read-less";

const SilentHill2 = (props) => {
  const { monsterData } = props;
  console.log("Monster Data", monsterData);
  // const [monsterData, setMonsterData] = useState([]);
  // useEffect(() => {
  //   const monsterFetchUrl =
  //     "https://pacific-journey-89141.herokuapp.com/api/silent-hill-monsters";

  //   const fetchData = async () => {
  //     const response = await fetch(monsterFetchUrl);
  //     const data = await response.json();
  //     console.log(data.data);
  //     console.log(data.data[0].attributes?.silenthill1monsters);
  //     setMonsterData(data.data[0].attributes?.silenthill1monsters);
  //   };
  //   fetchData();
  // }, []);

  return (
    <div className={styles.mainBackgroundDiv}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        {/* bootstrap 5 */}
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        ></link>
        <script
          async
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
          crossOrigin="anonymous"
        ></script>
      </Head>
      <nav className="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <div className="container-fluid">
          <Link href="#">
            <a className="navbar-brand">Silent Hill 1</a>
          </Link>
          <button
            className="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span className="navbar-toggler-icon" />
          </button>
          <div className="collapse navbar-collapse" id="navbarNavDropdown">
            <ul className="navbar-nav">
              <li className="nav-item">
                <Link href="/">
                  <a className="nav-link active" aria-current="page">
                    Home
                  </a>
                </Link>
              </li>
              {/* <li className="nav-item">
                <Link href="#">
                  <a className="nav-link">Features</a>
                </Link>
              </li>
              <li className="nav-item">
                <Link href="#">
                  <a className="nav-link">Pricing</a>
                </Link>
              </li>
              <li className="nav-item dropdown">
                <Link href="#">
                  <a
                    className="nav-link dropdown-toggle"
                    id="navbarDropdownMenuLink"
                    role="button"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    Dropdown link
                  </a>
                </Link>
                <ul
                  className="dropdown-menu"
                  aria-labelledby="navbarDropdownMenuLink"
                >
                  <li>
                    <Link href="#">
                      <a className="dropdown-item">Action</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="#">
                      <a className="dropdown-item">Another action</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="#">
                      <a className="dropdown-item">Something else here</a>
                    </Link>
                  </li>
                </ul>
              </li> */}
            </ul>
          </div>
        </div>
      </nav>

      <div className="row" style={{ paddingTop: "5%" }}>
        {monsterData?.map((monster, index) => {
          const myLoader = ({ src }) => {
            return `${monster.page_link}`;
          };
          return (
            <div
              key={index}
              className="card col-md-3 col-sm-12"
              style={{ width: "18rem", margin: "1em" }}
            >
              <div
                style={{
                  height: "15em",
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                }}
                className="card-img-top"
              >
                <Image
                  // className={style.image_style}
                  // style={{
                  //   position: "absolute",
                  //   inset: "0px",
                  //   margin: "auto",
                  //   width: "100%",
                  //   height: "100%",
                  //   maxWidth: "50%",
                  // }}
                  // loader={myLoader}
                  src={monster?.image_link}
                  alt="..."
                  width={500}
                  height={400}
                  // layout="fill"
                />
              </div>

              <div className="card-body" style={{ height: "50%" }}>
                <h5 className="card-title">{monster?.monsterName}</h5>
                <p className="card-text">{monster?.description}</p>
              </div>
              {/* <ul className="list-group list-group-flush">
              <li className="list-group-item">An item</li>
              <li className="list-group-item">A second item</li>
              <li className="list-group-item">A third item</li>
            </ul> */}
              <div className="card-body">
                <Link href={monster?.page_link}>
                  <a target="_blank" rel="noreferrer" className="card-link">
                    Read More
                  </a>
                </Link>
                {/* <a href="#" className="card-link">
                Another link
              </a> */}
              </div>
            </div>
          );
        })}
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default SilentHill2;
